#!/bin/bash
#
# A script that starts ferret

# Increase open file descriptors limit
ulimit -n 32000
date >> /tmp/ferret.ulimit.a.latest
ulimit -a >> /tmp/ferret.ulimit.a.latest

# This oneliner gets path of the directory where this script is located
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd $DIR

# THis gets name of the directory
RAILS=${PWD##*/}

# Start ferret
ruby script/ferret_server run -e production -R $DIR &
echo $! > /var/run/$RAILS.pid
